#pragma once

namespace callbacks {
	void SkinUpdate( );
	void ForceFullUpdate( );
	void ToggleThirdPerson( );
	void ToggleFakeLatency( );
    void ToggleKillfeed( );
	void SaveHotkeys( );
	void ConfigLoad1( );
	void ConfigLoad2( );
	void ConfigLoad3( );
	void ConfigLoad4( );
	void ConfigLoad5( );
	void ConfigLoad6( );
	void ConfigLoad( );
	void ConfigSave( );
	void HiddenCvar();

	bool IsBaimHealth( );
	bool IsFovOn( );
	bool IsHitchanceOn( );
	bool IsPenetrationOn( );
	bool IsMultipointOn( );
	bool IsMultipointBodyOn( );
	bool IsAutoSelected();
	bool IsScoutSelected();
	bool IsAwpSelected();
	bool IsDefaultSelected();
	bool IsAntiAimModeStand();
	bool IsUsingStandCustom();
	bool IsUsingCustomBreaker();
	bool HasStandYaw();
	bool DistortionOn();
	bool IsStandYawJitter();
	bool IsStandYawRotate();
	bool IsStandYawRandom();
	bool IsStandDirAuto();
	bool IsStandDirCustom();
	bool IsUsingDistortion();
	bool IsShowingManual();
	bool IsFakeAntiAimRelative();
	bool IsFakeAntiAimJitter();
	void ToggleDesync();
	void ToggleDesyncInvert();
	void SetManualLeft();
	void SetManualRight();
	void SetManualBack();

	bool IsConfigMM( );
	bool IsConfigNS( );
	bool IsConfig1( );
	bool IsConfig2( );
	bool IsConfig3( );
	bool IsConfig4( );
	bool IsConfig5( );
	bool IsConfig6( );
	bool IsUsingAmbientLight();
	bool IsUsingNightMode();
	bool IsChamsSelection0();
	bool LocalGlowChamsSelection();
	bool IsChamsSelection1();
	bool EnemyGlowChamsSelection();
	bool IsChamsSelection2();
	bool IsChamsSelection3();
	bool IsChamsSelection4();
	bool IsChamsSelection5();
	bool IsChamsSelection6();
	bool IsChamsSelection7();
	bool FakeGlowChamsSelection();
	void ToggleDoubletap();
	void ToggleDamage();
	// weapon cfgs.
	bool DEAGLE( );
	bool ELITE( );
	bool FIVESEVEN( );
	bool GLOCK( );
	bool AK47( );
	bool AUG( );
	bool AWP( );
	bool FAMAS( );
	bool G3SG1( );
	bool GALIL( );
	bool M249( );
	bool M4A4( );
	bool MAC10( );
	bool P90( );
	bool UMP45( );
	bool XM1014( );
	bool BIZON( );
	bool MAG7( );
	bool NEGEV( );
	bool SAWEDOFF( );
	bool TEC9( );
	bool P2000( );
	bool MP7( );
	bool MP9( );
	bool NOVA( );
	bool P250( );
	bool SCAR20( );
	bool SG553( );
	bool SSG08( );
	bool M4A1S( );
	bool USPS( );
	bool CZ75A( );
	bool REVOLVER( );
	bool KNIFE_BAYONET( );
	bool KNIFE_FLIP( );
	bool KNIFE_GUT( );
	bool KNIFE_KARAMBIT( );
	bool KNIFE_M9_BAYONET( );
	bool KNIFE_HUNTSMAN( );
	bool KNIFE_FALCHION( );
	bool KNIFE_BOWIE( );
	bool KNIFE_BUTTERFLY( );
	bool KNIFE_SHADOW_DAGGERS( );
	bool AUTO_STOP( );
}